version: "3.9"

services:
  app:
    image: flask_api:latest
    container_name: flask_api_container
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "5000:5000"
#    by using volumes we sync our local code with our container, so we don't need to rebuild every time our container
    volumes:
      - ./server:/server
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      db:
        condition: service_healthy

    command: ["flask", "run", "--host", "0.0.0.0"]

  db:
    image: postgres:13-alpine
    container_name: db-postgres
    ports:
      - "5433:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
      - ./instance/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "devdb", "-U", "devuser" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data: