name: CI
on: [ push ]
#on:
#  pull_request:
#    branches:
#      - master
#    types:
#      - opened

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

  test:
    name: Test
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Test
        run: docker-compose run app sh -c "python manage.py test"

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
        continue-on-error: true

  show-logs:
    name: Show logs
    runs-on: ubuntu-20.04
    needs: [build, test, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show logs
        run: docker-compose logs
