name: CI
on: [ push ]
#on:
#  pull_request:
#    branches:
#      - master
#    types:
#      - opened
jobs:
  test-lint:
    name: Build Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Test
        run: docker-compose exec -T app sh -c "python manage.py test"

      - name: Lint
        run: | 
          docker-compose exec -T app sh -c "flake8 --ignore=E501,E231 *.py && pylint --disable=C0301 --disable=C0415 *.py"
        continue-on-error: true

      - name: Show logs
        run: docker-compose logs