name: CI Pipeline
# set on when pull request is open to master or production branch, and when push to master or production branch but lunch Publish images to docker hub step only when pull request is merged to master or production branch successfully
on:
  push:
    branches:
      - master
      - production
  pull_request:
    branches:
      - master
      - production
    types:
      - opened
      - synchronize


permissions:
  contents: read
jobs:
  ci-pipeline:
    name: CI Pipeline
    runs-on: ubuntu-20.04
    permissions:
      checks: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Lint
        run: |
          docker-compose exec -T app sh -c "flake8 --ignore=E501,E231 *.py && pylint --disable=C0301 --disable=C0415 *.py"
        continue-on-error: true

      - name: Run Test
        run: docker-compose run app sh -c "python -m pytest --verbose --junit-xml=junit.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true

      - name: Coverage
        run: docker-compose exec -T app sh -c "pytest --cov=server tests/*"

#  delivery:
#    needs: [ ci-pipeline ]
##    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Publish images to docker hub
#        run: |
#          echo "github.ref: ${{ github.ref }}"
#          echo "github.sha: ${{ github.sha }}"
#          echo "github.event_name: ${{ github.event_name }}"
#          echo "github.repository: ${{ github.repository }}"
#          echo "github.event.pull_request.merged: ${{ github.event.pull_request.merged }}"
#          echo "github.event.pull_request.head.ref: ${{ github.event.pull_request.head.ref }}"
#
#          docker tag flask_api:latest ${{ secrets.DOCKERHUB_USER }}/flask_api_template:latest
#          docker push ${{ secrets.DOCKERHUB_USER }}/flask_api_template:latest
#


