name: Continuous integration pipeline
on: [push]


permissions:
  contents: read
#on:
#  pull_request:
#    branches:
#      - master
#    types:
#      - opened
jobs:
  ci-pipeline:
    name: Build,Test,Coverage and Lint
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Lint
        run: |
          docker-compose exec -T app sh -c "flake8 --ignore=E501,E231 *.py && pylint --disable=C0301 --disable=C0415 *.py"
        continue-on-error: true

      - name: Run Test
        run: docker-compose run app sh -c "python -m pytest --verbose --junit-xml=junit.xml"

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/junit.xml'
          detailed_summary: true
          include_passed: true

      - name: Coverage
        run: docker-compose exec -T app sh -c "pytest --cov=server tests/*"

      - name: Publish images to docker hub
        run: |
          docker-compose exec -T app sh -c "docker tag flask_api:latest ${{ secrets.DOCKERHUB_USER }}/flask_api_template:latest"
          docker-compose exec -T app sh -c "docker push ${{ secrets.DOCKERHUB_USER }}/flask_api_template:latest"

      - name: Stop Docker Compose
        run: docker-compose down

